// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Appends events to an existing DataSet.
public struct AppendEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Events to be appended.
  ///
  /// Note:
  ///
  /// 0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
  ///    in the results of `list` method; otherwise, all events from
  ///    the append request will be dropped, and a `NOT_FOUND` status will be
  ///    returned.
  /// 0. All events in a single request must have the same
  ///    [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
  ///    `INVALID_ARGUMENT` status will be returned.
  /// 0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
  ///    should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
  ///    returned.
  /// 0. The events must be newer than the current time minus
  ///    [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  /// [google.cloud.timeseriesinsights.v1.DataSet.ttl]: <doc:DataSet/ttl>
  /// [google.cloud.timeseriesinsights.v1.Event.group_id]: <doc:Event/groupId>
  public var events: [Event] = []

  /// Required. The DataSet to which we want to append to in the format of
  /// "projects/{project}/datasets/{dataset}"
  public var dataset: Swift.String = Swift.String()

  /// Initialize a new instance of `AppendEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppendEventsRequest().with { $0.events = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.AppendEventsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
