// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Appends events to an existing DataSet.
public struct AppendEventsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Events to be appended.
  ///
  /// Note:
  ///
  /// 0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
  ///    in the results of `list` method; otherwise, all events from
  ///    the append request will be dropped, and a `NOT_FOUND` status will be
  ///    returned.
  /// 0. All events in a single request must have the same
  ///    [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
  ///    `INVALID_ARGUMENT` status will be returned.
  /// 0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
  ///    should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
  ///    returned.
  /// 0. The events must be newer than the current time minus
  ///    [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  /// [google.cloud.timeseriesinsights.v1.DataSet.ttl]: <doc:DataSet/ttl>
  /// [google.cloud.timeseriesinsights.v1.Event.group_id]: <doc:Event/groupId>
  public var events: [Event] = []

  /// Required. The DataSet to which we want to append to in the format of
  /// "projects/{project}/datasets/{dataset}"
  public var dataset: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppendEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppendEventsRequest().with { $0.events = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let events = CodingKeys(stringValue: "events")
    static let dataset = CodingKeys(stringValue: "dataset")

    static let _knownKeys: Set<Swift.String> = [
      "events",
      "dataset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Event].self, forKey: .events) {
      self.events = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataset) {
      self.dataset = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.events, forKey: .events)
    try container.encode(self.dataset, forKey: .dataset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.AppendEventsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
