// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Mapping of BigQuery columns to timestamp, group_id and dimensions.
public struct BigqueryMapping: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The column which should be used as the event timestamps. If not specified
  /// 'Timestamp' is used by default. The column may have TIMESTAMP or INT64
  /// type (the latter is interpreted as microseconds since the Unix epoch).
  public var timestampColumn: Swift.String = Swift.String()

  /// The column which should be used as the group ID (grouping events into
  /// sessions). If not specified 'GroupId' is used by default, if the input
  /// table does not have such a column, random unique group IDs are
  /// generated automatically (different group ID per input row).
  public var groupIdColumn: Swift.String = Swift.String()

  /// The list of columns that should be translated to dimensions. If empty,
  /// all columns are translated to dimensions. The timestamp and group_id
  /// columns should not be listed here again. Columns are expected to have
  /// primitive types (STRING, INT64, FLOAT64 or NUMERIC).
  public var dimensionColumn: [Swift.String] = []

  /// Initialize a new instance of `BigqueryMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigqueryMapping().with { $0.timestampColumn = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.BigqueryMapping"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
