// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Mapping of BigQuery columns to timestamp, group_id and dimensions.
public struct BigqueryMapping: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The column which should be used as the event timestamps. If not specified
  /// 'Timestamp' is used by default. The column may have TIMESTAMP or INT64
  /// type (the latter is interpreted as microseconds since the Unix epoch).
  public var timestampColumn: Swift.String = Swift.String()

  /// The column which should be used as the group ID (grouping events into
  /// sessions). If not specified 'GroupId' is used by default, if the input
  /// table does not have such a column, random unique group IDs are
  /// generated automatically (different group ID per input row).
  public var groupIdColumn: Swift.String = Swift.String()

  /// The list of columns that should be translated to dimensions. If empty,
  /// all columns are translated to dimensions. The timestamp and group_id
  /// columns should not be listed here again. Columns are expected to have
  /// primitive types (STRING, INT64, FLOAT64 or NUMERIC).
  public var dimensionColumn: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BigqueryMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigqueryMapping().with { $0.timestampColumn = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let timestampColumn = CodingKeys(stringValue: "timestampColumn")
    static let groupIdColumn = CodingKeys(stringValue: "groupIdColumn")
    static let dimensionColumn = CodingKeys(stringValue: "dimensionColumn")

    static let _knownKeys: Set<Swift.String> = [
      "timestampColumn",
      "groupIdColumn",
      "dimensionColumn",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timestampColumn) {
      self.timestampColumn = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .groupIdColumn) {
      self.groupIdColumn = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dimensionColumn) {
      self.dimensionColumn = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.timestampColumn, forKey: .timestampColumn)
    try container.encode(self.groupIdColumn, forKey: .groupIdColumn)
    try container.encode(self.dimensionColumn, forKey: .dimensionColumn)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.BigqueryMapping"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
