// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Forecast result for a given slice.
public struct EvaluatedSlice: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Values for all categorical dimensions that uniquely identify this slice.
  public var dimensions: [PinnedDimension] = []

  /// The actual value at the detection time (see
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]).
  ///
  /// **NOTE**: This value can be an estimate, so it should not be used as a
  /// source of truth.
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  public var detectionPointActual: Swift.Double? = nil

  /// The expected value at the detection time, which is obtained by forecasting
  /// on the historical time series.
  public var detectionPointForecast: Swift.Double? = nil

  /// How much our forecast model expects the detection point actual will
  /// deviate from its forecasted value based on how well it fit the input time
  /// series.
  ///
  /// In general, we expect the `detectionPointActual` to
  /// be in the `[detectionPointForecast - expectedDeviation,
  /// detectionPointForecast + expectedDeviation]` range. The more the actual
  /// value is outside this range, the more statistically significant the
  /// anomaly is.
  ///
  /// The expected deviation is always positive.
  public var expectedDeviation: Swift.Double? = nil

  /// Summarizes how significant the change between the actual and forecasted
  /// detection points are compared with the historical patterns observed on the
  /// [history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] time series.
  ///
  /// Defined as *|a - f| / (e + nt)*, where:
  ///
  /// - *a* is the [detectionPointActual][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual].
  /// - *f* is the [detectionPointForecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast].
  /// - *e* is the [expectedDeviation][google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation].
  /// - *nt` is the [noiseThreshold][google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold].
  ///
  /// Anomaly scores between different requests and datasets are comparable. As
  /// a guideline, the risk of a slice being an anomaly based on the anomaly
  /// score is:
  ///
  /// - **Very High** if `anomalyScore` > 5.
  /// - **High** if the `anomalyScore` is in the [2, 5] range.
  /// - **Medium** if the `anomalyScore` is in the [1, 2) range.
  /// - **Low** if the `anomalyScore` is < 1.
  ///
  /// If there were issues evaluating this slice, then the anomaly score will be
  /// set to -1.0 and the [status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status] field will contain details on what
  /// went wrong.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual]: <doc:EvaluatedSlice/detectionPointActual>
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast]: <doc:EvaluatedSlice/detectionPointForecast>
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation]: <doc:EvaluatedSlice/expectedDeviation>
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.history]: <doc:EvaluatedSlice/history>
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.status]: <doc:EvaluatedSlice/status>
  /// [google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold]: <doc:ForecastParams/noiseThreshold>
  public var anomalyScore: Swift.Double? = nil

  /// The actual values in the `[`
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `-`
  /// [forecastHistory][google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]`,`
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `]` time
  /// range.
  ///
  /// **NOTE**: This field is only populated if
  /// [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries]: <doc:QueryDataSetRequest/returnTimeseries>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]: <doc:TimeseriesParams/forecastHistory>
  public var history: Timeseries? = nil

  /// The forecasted values in the `[`
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `+`
  /// [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]`,`
  /// [forecastParams.horizonTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params] `]` time
  /// range.
  ///
  /// **NOTE**: This field is only populated if
  /// [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params]: <doc:QueryDataSetRequest/forecastParams>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries]: <doc:QueryDataSetRequest/returnTimeseries>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]: <doc:TimeseriesParams/granularity>
  public var forecast: Timeseries? = nil

  /// Evaluation status. Contains an error message if the `anomalyScore` is < 0.
  ///
  /// Possible error messages:
  ///
  /// - **"Time series too sparse"**: The returned time series for this slice did
  /// not contain enough data points (we require a minimum of 10).
  /// - **"Not enough recent time series points"**: The time series contains the
  /// minimum of 10 points, but there are not enough close in time to the
  /// detection point.
  /// - **"Missing detection point data"**: There were not events to be
  /// aggregated within the `[detectionTime, detectionTime + granularity]` time
  /// interval, so we don't have an actual value with which we can compare our
  /// prediction.
  /// - **"Data retrieval error"**: We failed to retrieve the time series data
  /// for this slice and could not evaluate it successfully. Should be a
  /// transient error.
  /// - **"Internal server error"**: Internal unexpected error.
  public var status: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EvaluatedSlice`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluatedSlice().with { $0.dimensions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dimensions = CodingKeys(stringValue: "dimensions")
    static let detectionPointActual = CodingKeys(stringValue: "detectionPointActual")
    static let detectionPointForecast = CodingKeys(stringValue: "detectionPointForecast")
    static let expectedDeviation = CodingKeys(stringValue: "expectedDeviation")
    static let anomalyScore = CodingKeys(stringValue: "anomalyScore")
    static let history = CodingKeys(stringValue: "history")
    static let forecast = CodingKeys(stringValue: "forecast")
    static let status = CodingKeys(stringValue: "status")

    static let _knownKeys: Set<Swift.String> = [
      "dimensions",
      "detectionPointActual",
      "detectionPointForecast",
      "expectedDeviation",
      "anomalyScore",
      "history",
      "forecast",
      "status",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([PinnedDimension].self, forKey: .dimensions) {
      self.dimensions = value
    }
    self.detectionPointActual = try container.decodeIfPresent(
      Swift.Double.self, forKey: .detectionPointActual)
    self.detectionPointForecast = try container.decodeIfPresent(
      Swift.Double.self, forKey: .detectionPointForecast)
    self.expectedDeviation = try container.decodeIfPresent(
      Swift.Double.self, forKey: .expectedDeviation)
    self.anomalyScore = try container.decodeIfPresent(Swift.Double.self, forKey: .anomalyScore)
    self.history = try container.decodeIfPresent(Timeseries.self, forKey: .history)
    self.forecast = try container.decodeIfPresent(Timeseries.self, forKey: .forecast)
    self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dimensions, forKey: .dimensions)
    try container.encodeIfPresent(self.detectionPointActual, forKey: .detectionPointActual)
    try container.encodeIfPresent(self.detectionPointForecast, forKey: .detectionPointForecast)
    try container.encodeIfPresent(self.expectedDeviation, forKey: .expectedDeviation)
    try container.encodeIfPresent(self.anomalyScore, forKey: .anomalyScore)
    try container.encodeIfPresent(self.history, forKey: .history)
    try container.encodeIfPresent(self.forecast, forKey: .forecast)
    try container.encodeIfPresent(self.status, forKey: .status)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EvaluatedSlice"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
