// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for evaluateTimeseries.
public struct EvaluateTimeseriesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Client project name in the format of 'projects/{project}'.
  public var parent: Swift.String = Swift.String()

  /// Evaluate this time series without requiring it was previously loaded in
  /// a data set.
  ///
  /// The evaluated time series point is the last one, analogous to calling
  /// evaluateSlice or query with
  /// [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] set to
  /// `timeseries.point(timeseries.point_size() - 1).time`.
  ///
  /// The length of the time series must be at least 10.
  ///
  /// All points must have the same time offset relative to the granularity. For
  /// example, if the [granularity][google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest.granularity] is "5s", then the following
  /// point.time sequences are valid:
  /// - "100s", "105s", "120s", "125s" (no offset)
  /// - "102s", "107s", "122s", "127s" (offset is "2s")
  /// However, the following sequence is invalid as it has inconsistent offsets:
  /// - "100s", "105s", "122s", "127s" (offsets are either "0s" or "2s")
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time]: <doc:EvaluateSliceRequest/detectionTime>
  /// [google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest.granularity]: <doc:EvaluateTimeseriesRequest/granularity>
  public var timeseries: Timeseries? = nil

  /// The granularity of the time series (time distance between two consecutive
  /// points).
  public var granularity: GoogleWKT.Duration? = nil

  /// The forecast parameters.
  public var forecastParams: ForecastParams? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EvaluateTimeseriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluateTimeseriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let timeseries = CodingKeys(stringValue: "timeseries")
    static let granularity = CodingKeys(stringValue: "granularity")
    static let forecastParams = CodingKeys(stringValue: "forecastParams")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "timeseries",
      "granularity",
      "forecastParams",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.timeseries = try container.decodeIfPresent(Timeseries.self, forKey: .timeseries)
    self.granularity = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .granularity)
    self.forecastParams = try container.decodeIfPresent(
      ForecastParams.self, forKey: .forecastParams)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.timeseries, forKey: .timeseries)
    try container.encodeIfPresent(self.granularity, forKey: .granularity)
    try container.encodeIfPresent(self.forecastParams, forKey: .forecastParams)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
