// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for evaluateSlice.
public struct EvaluateSliceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Loaded DataSet to be queried in the format of
  /// "projects/{project}/datasets/{dataset}"
  public var dataset: Swift.String = Swift.String()

  /// Required. Dimensions with pinned values that specify the slice for which we will
  /// fetch the time series.
  public var pinnedDimensions: [PinnedDimension] = []

  /// Required. This is the point in time that we want to probe for anomalies.
  ///
  /// See documentation for
  /// [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  public var detectionTime: GoogleWKT.Timestamp? = nil

  /// Parameters controlling how we will build the time series used to predict
  /// the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time]: <doc:EvaluateSliceRequest/detectionTime>
  public var timeseriesParams: TimeseriesParams? = nil

  /// Parameters that control the time series forecasting models, such as the
  /// sensitivity of the anomaly detection.
  public var forecastParams: ForecastParams? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EvaluateSliceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluateSliceRequest().with { $0.dataset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dataset = CodingKeys(stringValue: "dataset")
    static let pinnedDimensions = CodingKeys(stringValue: "pinnedDimensions")
    static let detectionTime = CodingKeys(stringValue: "detectionTime")
    static let timeseriesParams = CodingKeys(stringValue: "timeseriesParams")
    static let forecastParams = CodingKeys(stringValue: "forecastParams")

    static let _knownKeys: Set<Swift.String> = [
      "dataset",
      "pinnedDimensions",
      "detectionTime",
      "timeseriesParams",
      "forecastParams",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataset) {
      self.dataset = value
    }
    if let value = try container.decodeIfPresent([PinnedDimension].self, forKey: .pinnedDimensions)
    {
      self.pinnedDimensions = value
    }
    self.detectionTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .detectionTime)
    self.timeseriesParams = try container.decodeIfPresent(
      TimeseriesParams.self, forKey: .timeseriesParams)
    self.forecastParams = try container.decodeIfPresent(
      ForecastParams.self, forKey: .forecastParams)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dataset, forKey: .dataset)
    try container.encode(self.pinnedDimensions, forKey: .pinnedDimensions)
    try container.encodeIfPresent(self.detectionTime, forKey: .detectionTime)
    try container.encodeIfPresent(self.timeseriesParams, forKey: .timeseriesParams)
    try container.encodeIfPresent(self.forecastParams, forKey: .forecastParams)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EvaluateSliceRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
