// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for evaluateTimeseries.
public struct EvaluateTimeseriesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Client project name in the format of 'projects/{project}'.
  public var parent: Swift.String = Swift.String()

  /// Evaluate this time series without requiring it was previously loaded in
  /// a data set.
  ///
  /// The evaluated time series point is the last one, analogous to calling
  /// evaluateSlice or query with
  /// [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] set to
  /// `timeseries.point(timeseries.point_size() - 1).time`.
  ///
  /// The length of the time series must be at least 10.
  ///
  /// All points must have the same time offset relative to the granularity. For
  /// example, if the [granularity][google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest.granularity] is "5s", then the following
  /// point.time sequences are valid:
  /// - "100s", "105s", "120s", "125s" (no offset)
  /// - "102s", "107s", "122s", "127s" (offset is "2s")
  /// However, the following sequence is invalid as it has inconsistent offsets:
  /// - "100s", "105s", "122s", "127s" (offsets are either "0s" or "2s")
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time]: <doc:EvaluateSliceRequest/detectionTime>
  /// [google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest.granularity]: <doc:EvaluateTimeseriesRequest/granularity>
  public var timeseries: Timeseries? = nil

  /// The granularity of the time series (time distance between two consecutive
  /// points).
  public var granularity: GoogleCloudWkt.Duration? = nil

  /// The forecast parameters.
  public var forecastParams: ForecastParams? = nil

  /// Initialize a new instance of `EvaluateTimeseriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluateTimeseriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EvaluateTimeseriesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
