// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for evaluateSlice.
public struct EvaluateSliceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Loaded DataSet to be queried in the format of
  /// "projects/{project}/datasets/{dataset}"
  public var dataset: Swift.String = Swift.String()

  /// Required. Dimensions with pinned values that specify the slice for which we will
  /// fetch the time series.
  public var pinnedDimensions: [PinnedDimension] = []

  /// Required. This is the point in time that we want to probe for anomalies.
  ///
  /// See documentation for
  /// [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  public var detectionTime: GoogleCloudWkt.Timestamp? = nil

  /// Parameters controlling how we will build the time series used to predict
  /// the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time]: <doc:EvaluateSliceRequest/detectionTime>
  public var timeseriesParams: TimeseriesParams? = nil

  /// Parameters that control the time series forecasting models, such as the
  /// sensitivity of the anomaly detection.
  public var forecastParams: ForecastParams? = nil

  /// Initialize a new instance of `EvaluateSliceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluateSliceRequest().with { $0.dataset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EvaluateSliceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
