// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents an event dimension.
public struct EventDimension: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Dimension name.
  ///
  /// **NOTE**: `EventDimension` names must be composed of alphanumeric
  /// characters only, and are case insensitive. Unicode characters are *not*
  /// supported. The underscore '_' is also allowed.
  public var name: Swift.String = Swift.String()

  /// Dimension value.
  ///
  /// **NOTE**: All entries of the dimension `name` must have the same `value`
  /// type.
  public var value: OneOf_Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `EventDimension`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventDimension().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let stringVal = CodingKeys(stringValue: "stringVal")
    static let longVal = CodingKeys(stringValue: "longVal")
    static let boolVal = CodingKeys(stringValue: "boolVal")
    static let doubleVal = CodingKeys(stringValue: "doubleVal")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "stringVal",
      "longVal",
      "boolVal",
      "doubleVal",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let stringVal = try container.decodeIfPresent(Swift.String.self, forKey: .stringVal) {
      try valueCheckAndSet(.stringVal(stringVal))
    }
    if let longVal = try container.decodeIfPresent(Swift.Int64.self, forKey: .longVal) {
      try valueCheckAndSet(.longVal(longVal))
    }
    if let boolVal = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolVal) {
      try valueCheckAndSet(.boolVal(boolVal))
    }
    if let doubleVal = try container.decodeIfPresent(Swift.Double.self, forKey: .doubleVal) {
      try valueCheckAndSet(.doubleVal(doubleVal))
    }
    self.value = value
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.value {
      switch choice {
      case .stringVal(let value):
        try container.encode(value, forKey: .stringVal)
      case .longVal(let value):
        try container.encode(value, forKey: .longVal)
      case .boolVal(let value):
        try container.encode(value, forKey: .boolVal)
      case .doubleVal(let value):
        try container.encode(value, forKey: .doubleVal)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Dimension value.
  ///
  /// **NOTE**: All entries of the dimension `name` must have the same `value`
  /// type.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// String representation.
    ///
    /// **NOTE**: String values are case insensitive. Unicode characters are
    /// supported.
    case stringVal(Swift.String)
    /// Long representation.
    case longVal(Swift.Int64)
    /// Bool representation.
    case boolVal(Swift.Bool)
    /// Double representation.
    case doubleVal(Swift.Double)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.EventDimension"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
