// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Parameters that control the sensitivity and other options for the time series
/// forecast.
public struct ForecastParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Penalize variations between the actual and forecasted values smaller than
  /// this. For more information about how this parameter affects the score, see
  /// the [anomalyScore](EvaluatedSlice.anomaly_score) formula.
  ///
  /// Intuitively, anomaly scores summarize how statistically significant the
  /// change between the actual and forecasted value is compared with what we
  /// expect the change to be (see
  /// [expectedDeviation](EvaluatedSlice.expected_deviation)). However, in
  /// practice, depending on the application, changes smaller than certain
  /// absolute values, while statistically significant, may not be important.
  ///
  /// This parameter allows us to penalize such low absolute value changes.
  ///
  /// Must be in the (0.0, inf) range.
  ///
  /// If unspecified, it defaults to 0.000001.
  public var noiseThreshold: Swift.Double? = nil

  /// Optional. Specifying any known seasonality/periodicity in the time series
  /// for the slices we will analyze can improve the quality of the results.
  ///
  /// If unsure, simply leave it unspecified by not setting a value for this
  /// field.
  ///
  /// If your time series has multiple seasonal patterns, then set it to the most
  /// granular one (e.g. if it has daily and weekly patterns, set this to DAILY).
  public var seasonalityHint: ForecastParams.Period = ForecastParams.Period()

  /// Optional. The length of the returned [forecasted
  /// timeseries][EvaluatedSlice.forecast].
  ///
  /// This duration is currently capped at 100 x
  /// [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity].
  ///
  /// Example: If the detection point is set to "2020-12-27T00:00:00Z", the
  /// [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity] to "3600s" and the
  /// horizon_duration to "10800s", then we will generate 3 time
  /// series points (from "2020-12-27T01:00:00Z" to "2020-12-27T04:00:00Z"), for
  /// which we will return their forecasted values.
  ///
  /// Note: The horizon time is only used for forecasting not for anormaly
  /// detection. To detect anomalies for multiple points of time,
  /// simply send multiple queries with those as
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
  ///
  /// [EvaluatedSlice.forecast]: <doc:EvaluatedSlice/forecast>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]: <doc:TimeseriesParams/granularity>
  public var horizonDuration: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `ForecastParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ForecastParams().with { $0.noiseThreshold = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A time period of a fixed interval.
  public enum Period: Codable, Equatable, Sendable {
    /// Unknown or simply not given.
    case unspecified
    /// 24 hours
    case daily
    /// 7 days
    case weekly
    /// 30 days
    case monthly
    /// 365 days
    case yearly
    /// 1 hour
    case hourly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .daily: return 1
      case .weekly: return 2
      case .monthly: return 3
      case .yearly: return 4
      case .hourly: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERIOD_UNSPECIFIED"
      case .daily: return "DAILY"
      case .weekly: return "WEEKLY"
      case .monthly: return "MONTHLY"
      case .yearly: return "YEARLY"
      case .hourly: return "HOURLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Period/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERIOD_UNSPECIFIED": self = .unspecified
      case "HOURLY": self = .hourly
      case "DAILY": self = .daily
      case "WEEKLY": self = .weekly
      case "MONTHLY": self = .monthly
      case "YEARLY": self = .yearly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Period/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .daily
      case 2: self = .weekly
      case 3: self = .monthly
      case 4: self = .yearly
      case 5: self = .hourly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .daily: return try container.encode(1)
      case .weekly: return try container.encode(2)
      case .monthly: return try container.encode(3)
      case .yearly: return try container.encode(4)
      case .hourly: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.ForecastParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
