// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A categorical dimension fixed to a certain value.
public struct PinnedDimension: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the dimension for which we are fixing its value.
  public var name: Swift.String = Swift.String()

  /// Dimension value.
  ///
  /// **NOTE**: The `value` type must match that in the data with the same
  /// `dimension` as name.
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `PinnedDimension`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PinnedDimension().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case stringVal = "stringVal"
    case boolVal = "boolVal"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let stringVal = try container.decodeIfPresent(Swift.String.self, forKey: .stringVal) {
      try valueCheckAndSet(.stringVal(stringVal))
    }
    if let boolVal = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolVal) {
      try valueCheckAndSet(.boolVal(boolVal))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.value {
      switch choice {
      case .stringVal(let value):
        try container.encode(value, forKey: .stringVal)
      case .boolVal(let value):
        try container.encode(value, forKey: .boolVal)
      }
    }
  }

  /// Dimension value.
  ///
  /// **NOTE**: The `value` type must match that in the data with the same
  /// `dimension` as name.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// A string value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
    /// have their value field set to [string_val][google.cloud.timeseriesinsights.v1.EventDimension.string_val].
    ///
    /// [google.cloud.timeseriesinsights.v1.EventDimension]: <doc:EventDimension>
    /// [google.cloud.timeseriesinsights.v1.EventDimension.string_val]: <doc:EventDimension/stringVal>
    case stringVal(Swift.String)
    /// A bool value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
    /// have their value field set to [bool_val][google.cloud.timeseriesinsights.v1.EventDimension.bool_val].
    ///
    /// [google.cloud.timeseriesinsights.v1.EventDimension]: <doc:EventDimension>
    /// [google.cloud.timeseriesinsights.v1.EventDimension.bool_val]: <doc:EventDimension/boolVal>
    case boolVal(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.PinnedDimension"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
