// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response for a query executed by the system.
public struct QueryDataSetResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Loaded DataSet that was queried.
  public var name: Swift.String = Swift.String()

  /// Slices sorted in descending order by their
  /// [anomalyScore][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score].
  ///
  /// At most [numReturnedSlices][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]
  /// slices are present in this field.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score]: <doc:EvaluatedSlice/anomalyScore>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]: <doc:QueryDataSetRequest/numReturnedSlices>
  public var slices: [EvaluatedSlice] = []

  /// Initialize a new instance of `QueryDataSetResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryDataSetResponse().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.QueryDataSetResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
