// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for performing a query against a loaded DataSet.
public struct QueryDataSetRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Loaded DataSet to be queried in the format of
  /// "projects/{project}/datasets/{dataset}"
  public var name: Swift.String = Swift.String()

  /// Required. This is the point in time that we want to probe for anomalies.
  ///
  /// The corresponding [TimeseriesPoint][google.cloud.timeseriesinsights.v1.TimeseriesPoint] is referred to as the
  /// detection point.
  ///
  /// **NOTE**: As with any other time series point, the value is given by
  /// aggregating all events in the slice that are in the
  /// [detectionTime, detectionTime + granularity) time interval, where
  /// the granularity is specified in the
  /// [timeseriesParams.granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity] field.
  ///
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]: <doc:TimeseriesParams/granularity>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesPoint]: <doc:TimeseriesPoint>
  public var detectionTime: GoogleCloudWkt.Timestamp? = nil

  /// How many slices are returned in
  /// [QueryDataSetResponse.slices][google.cloud.timeseriesinsights.v1.QueryDataSetResponse.slices].
  ///
  /// The returned slices are tentatively the ones with the highest
  /// [anomaly scores][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score] in the dataset that match
  /// the query, but it is not guaranteed.
  ///
  /// Reducing this number will improve query performance, both in terms of
  /// latency and resource usage.
  ///
  /// Defaults to 50.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score]: <doc:EvaluatedSlice/anomalyScore>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetResponse.slices]: <doc:QueryDataSetResponse/slices>
  public var numReturnedSlices: Swift.Int32? = nil

  /// Parameters controlling how we will split the dataset into the slices that
  /// we will analyze.
  public var slicingParams: SlicingParams? = nil

  /// Parameters controlling how we will build the time series used to predict
  /// the [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] value for each slice.
  ///
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  public var timeseriesParams: TimeseriesParams? = nil

  /// Parameters that control the time series forecasting models, such as the
  /// sensitivity of the anomaly detection.
  public var forecastParams: ForecastParams? = nil

  /// If specified, we will return the actual and forecasted time for all
  /// returned slices.
  ///
  /// The time series are returned in the
  /// [EvaluatedSlice.history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] and
  /// [EvaluatedSlice.forecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.forecast] fields.
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.forecast]: <doc:EvaluatedSlice/forecast>
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.history]: <doc:EvaluatedSlice/history>
  public var returnTimeseries: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `QueryDataSetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryDataSetRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.QueryDataSetRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
