// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Parameters that control how we slice the dataset and, optionally, filter
/// slices that have some specific values on some dimensions (pinned dimensions).
public struct SlicingParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Dimensions over which we will group the events in slices. The names
  /// specified here come from the
  /// [EventDimension.name][google.cloud.timeseriesinsights.v1.EventDimension.name] field. At least
  /// one dimension name must be specified. All dimension names that do not exist
  /// in the queried `DataSet` will be ignored.
  ///
  /// Currently only dimensions that hold string values can be specified here.
  ///
  /// [google.cloud.timeseriesinsights.v1.EventDimension.name]: <doc:EventDimension/name>
  public var dimensionNames: [Swift.String] = []

  /// Optional. We will only analyze slices for which
  /// [EvaluatedSlice.dimensions][google.cloud.timeseriesinsights.v1.EvaluatedSlice.dimensions] contain all of the
  /// following pinned dimensions. A query with a pinned dimension `{ name: "d3"
  /// stringVal: "v3" }` will only analyze events which contain the dimension `{
  /// name: "d3" stringVal: "v3" }`.
  /// The [pinnedDimensions][google.cloud.timeseriesinsights.v1.SlicingParams.pinned_dimensions] and
  /// [dimensionNames][google.cloud.timeseriesinsights.v1.SlicingParams.dimension_names] fields can **not**
  /// share the same dimension names.
  ///
  /// Example a valid specification:
  ///
  /// ```json
  /// {
  ///   dimensionNames: ["d1", "d2"],
  ///   pinnedDimensions: [
  ///     { name: "d3" stringVal: "v3" },
  ///     { name: "d4" stringVal: "v4" }
  ///   ]
  /// }
  /// ```
  ///
  /// In the previous example we will slice the dataset by dimensions "d1",
  /// "d2", "d3" and "d4", but we will only analyze slices for which "d3=v3" and
  /// "d4=v4".
  ///
  /// The following example is **invalid** as "d2" is present in both
  /// dimensionNames and pinnedDimensions:
  ///
  /// ```json
  /// {
  ///   dimensionNames: ["d1", "d2"],
  ///   pinnedDimensions: [
  ///     { name: "d2" stringVal: "v2" },
  ///     { name: "d4" stringVal: "v4" }
  ///   ]
  /// }
  /// ```
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.dimensions]: <doc:EvaluatedSlice/dimensions>
  /// [google.cloud.timeseriesinsights.v1.SlicingParams.dimension_names]: <doc:SlicingParams/dimensionNames>
  /// [google.cloud.timeseriesinsights.v1.SlicingParams.pinned_dimensions]: <doc:SlicingParams/pinnedDimensions>
  public var pinnedDimensions: [PinnedDimension] = []

  /// Initialize a new instance of `SlicingParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlicingParams().with { $0.dimensionNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.SlicingParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
