// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

///
/// @Snippet(path: "TimeseriesInsightsControllerQuickstart")
public class TimeseriesInsightsControllerClient: Clients.TimeseriesInsightsControllerProtocol {
  let inner: any Clients.TimeseriesInsightsControllerStub

  /// Creates a new `TimeseriesInsightsControllerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TimeseriesInsightsControllerStub =
      try Clients.TimeseriesInsightsControllerTransport(options)
    inner = Clients.TimeseriesInsightsControllerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TimeseriesInsightsControllerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists [DataSets][google.cloud.timeseriesinsights.v1.DataSet] under the project.
  ///
  /// The order of the results is unspecified but deterministic. Newly created
  /// [DataSets][google.cloud.timeseriesinsights.v1.DataSet] will not necessarily be added to the end
  /// of this list.
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_ListDataSets")
  public func listDataSets(
    request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse {
    try await self.inner.listDataSets(request: request, options: options)
  }

  /// Lists [DataSets][google.cloud.timeseriesinsights.v1.DataSet] under the project.
  ///
  /// The order of the results is unspecified but deterministic. Newly created
  /// [DataSets][google.cloud.timeseriesinsights.v1.DataSet] will not necessarily be added to the end
  /// of this list.
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_ListDataSets")
  public func listDataSets(
    byItem: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DataSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDataSets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Create a [DataSet][google.cloud.timeseriesinsights.v1.DataSet] from data stored on Cloud
  /// Storage.
  ///
  /// The data must stay immutable while we process the
  /// [DataSet][google.cloud.timeseriesinsights.v1.DataSet] creation; otherwise, undefined outcomes
  /// might result.  For more information, see [DataSet][google.cloud.timeseriesinsights.v1.DataSet].
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_CreateDataSet")
  public func createDataSet(
    request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet {
    try await self.inner.createDataSet(request: request, options: options)
  }

  /// Delete a [DataSet][google.cloud.timeseriesinsights.v1.DataSet] from the system.
  ///
  /// **NOTE**: If the [DataSet][google.cloud.timeseriesinsights.v1.DataSet] is still being
  /// processed, it will be aborted and deleted.
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_DeleteDataSet")
  public func deleteDataSet(
    request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDataSet(request: request, options: options)
  }

  /// Append events to a `LOADED` [DataSet][google.cloud.timeseriesinsights.v1.DataSet].
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_AppendEvents")
  public func appendEvents(
    request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse {
    try await self.inner.appendEvents(request: request, options: options)
  }

  /// Execute a Timeseries Insights query over a loaded
  /// [DataSet][google.cloud.timeseriesinsights.v1.DataSet].
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_QueryDataSet")
  public func queryDataSet(
    request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse {
    try await self.inner.queryDataSet(request: request, options: options)
  }

  /// Evaluate an explicit slice from a loaded [DataSet][google.cloud.timeseriesinsights.v1.DataSet].
  ///
  /// [google.cloud.timeseriesinsights.v1.DataSet]: <doc:DataSet>
  ///
  /// @Snippet(path: "TimeseriesInsightsController_EvaluateSlice")
  public func evaluateSlice(
    request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
    try await self.inner.evaluateSlice(request: request, options: options)
  }

  /// Evaluate an explicit timeseries.
  ///
  /// @Snippet(path: "TimeseriesInsightsController_EvaluateTimeseries")
  public func evaluateTimeseries(
    request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
    try await self.inner.evaluateTimeseries(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TimeseriesInsightsControllerClient`.
  ///
  /// To mock `TimeseriesInsightsControllerClient` change your functions to receive
  /// `some TimeseriesInsightsControllerProtocol` or `any TimeseriesInsightsControllerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TimeseriesInsightsControllerProtocol {
    /// See `TimeseriesInsightsControllerClient.listDataSets`.
    func listDataSets(request: ListDataSetsRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse

    /// See `TimeseriesInsightsControllerClient.listDataSets`.
    func listDataSets(
      byItem: ListDataSetsRequest
    ) throws -> any AsyncSequence<DataSet, Swift.Error>

    /// See `TimeseriesInsightsControllerClient.listDataSets`.
    func listDataSets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DataSet, Swift.Error>

    /// See `TimeseriesInsightsControllerClient.createDataSet`.
    func createDataSet(request: CreateDataSetRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.DataSet

    /// See `TimeseriesInsightsControllerClient.createDataSet`.
    func createDataSet(
      parent: Swift.String,
      dataset: DataSet?,
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet

    /// See `TimeseriesInsightsControllerClient.deleteDataSet`.
    func deleteDataSet(request: DeleteDataSetRequest) async throws

    /// See `TimeseriesInsightsControllerClient.deleteDataSet`.
    func deleteDataSet(
      name: Swift.String,
    ) async throws

    /// See `TimeseriesInsightsControllerClient.appendEvents`.
    func appendEvents(request: AppendEventsRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse

    /// See `TimeseriesInsightsControllerClient.appendEvents`.
    func appendEvents(
      dataset: Swift.String,
      events: [Event],
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse

    /// See `TimeseriesInsightsControllerClient.queryDataSet`.
    func queryDataSet(request: QueryDataSetRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse

    /// See `TimeseriesInsightsControllerClient.evaluateSlice`.
    func evaluateSlice(request: EvaluateSliceRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice

    /// See `TimeseriesInsightsControllerClient.evaluateTimeseries`.
    func evaluateTimeseries(request: EvaluateTimeseriesRequest) async throws
      -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice

    /// See `TimeseriesInsightsControllerClient.listDataSets`.
    func listDataSets(
      request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse

    /// See `TimeseriesInsightsControllerClient.listDataSets`.
    func listDataSets(
      byItem: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DataSet, Swift.Error>

    /// See `TimeseriesInsightsControllerClient.createDataSet`.
    func createDataSet(
      request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet

    /// See `TimeseriesInsightsControllerClient.deleteDataSet`.
    func deleteDataSet(
      request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `TimeseriesInsightsControllerClient.appendEvents`.
    func appendEvents(
      request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse

    /// See `TimeseriesInsightsControllerClient.queryDataSet`.
    func queryDataSet(
      request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse

    /// See `TimeseriesInsightsControllerClient.evaluateSlice`.
    func evaluateSlice(
      request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice

    /// See `TimeseriesInsightsControllerClient.evaluateTimeseries`.
    func evaluateTimeseries(
      request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
  }
}

// Default implementations
extension Clients.TimeseriesInsightsControllerProtocol {
  public func listDataSets(request: ListDataSetsRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse
  {
    try await self.listDataSets(request: request, options: .init())
  }

  public func listDataSets(
    request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDataSets(
    byItem: ListDataSetsRequest
  ) throws -> any AsyncSequence<DataSet, Swift.Error> {
    try self.listDataSets(byItem: byItem, options: .init())
  }

  public func listDataSets(
    byItem: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DataSet, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDataSets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DataSet, Swift.Error> {
    let request = ListDataSetsRequest().with {
      $0.parent = parent
    }
    return try self.listDataSets(byItem: request)
  }

  public func createDataSet(request: CreateDataSetRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.DataSet
  {
    try await self.createDataSet(request: request, options: .init())
  }

  public func createDataSet(
    request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDataSet(
    parent: Swift.String,
    dataset: DataSet?,
  ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet {
    let request = CreateDataSetRequest().with {
      $0.parent = parent
      $0.dataset = dataset
    }
    return try await self.createDataSet(request: request)
  }

  public func deleteDataSet(request: DeleteDataSetRequest) async throws {
    try await self.deleteDataSet(request: request, options: .init())
  }

  public func deleteDataSet(
    request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDataSet(
    name: Swift.String,
  ) async throws {
    let request = DeleteDataSetRequest().with {
      $0.name = name
    }
    try await self.deleteDataSet(request: request)
  }

  public func appendEvents(request: AppendEventsRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse
  {
    try await self.appendEvents(request: request, options: .init())
  }

  public func appendEvents(
    request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func appendEvents(
    dataset: Swift.String,
    events: [Event],
  ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse {
    let request = AppendEventsRequest().with {
      $0.dataset = dataset
      $0.events = events
    }
    return try await self.appendEvents(request: request)
  }

  public func queryDataSet(request: QueryDataSetRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse
  {
    try await self.queryDataSet(request: request, options: .init())
  }

  public func queryDataSet(
    request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func evaluateSlice(request: EvaluateSliceRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
  {
    try await self.evaluateSlice(request: request, options: .init())
  }

  public func evaluateSlice(
    request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func evaluateTimeseries(request: EvaluateTimeseriesRequest) async throws
    -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
  {
    try await self.evaluateTimeseries(request: request, options: .init())
  }

  public func evaluateTimeseries(
    request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
