// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TimeseriesInsightsControllerLogging: TimeseriesInsightsControllerStub {
    let inner: any TimeseriesInsightsControllerStub
    let logger: Logger

    public init(_ inner: any TimeseriesInsightsControllerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-timeseriesinsights-v1"
      logger[metadataKey: "gcp.client.service"] = "timeseriesinsights"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TimeseriesInsightsController"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listDataSets(
      request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDataSets",
        action: {
          (r: ListDataSetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse
          in
          return try await self.inner.listDataSets(request: r, options: o)
        })
    }

    public func createDataSet(
      request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDataSet",
        action: {
          (r: CreateDataSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.DataSet
          in
          return try await self.inner.createDataSet(request: r, options: o)
        })
    }

    public func deleteDataSet(
      request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDataSet",
        action: {
          (r: DeleteDataSetRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDataSet(request: r, options: o)
        })
    }

    public func appendEvents(
      request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "appendEvents",
        action: {
          (r: AppendEventsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse
          in
          return try await self.inner.appendEvents(request: r, options: o)
        })
    }

    public func queryDataSet(
      request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryDataSet",
        action: {
          (r: QueryDataSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse
          in
          return try await self.inner.queryDataSet(request: r, options: o)
        })
    }

    public func evaluateSlice(
      request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
      try await self._intercept(
        request: request,
        options: options,
        name: "evaluateSlice",
        action: {
          (r: EvaluateSliceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
          in
          return try await self.inner.evaluateSlice(request: r, options: o)
        })
    }

    public func evaluateTimeseries(
      request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
      try await self._intercept(
        request: request,
        options: options,
        name: "evaluateTimeseries",
        action: {
          (r: EvaluateTimeseriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
          in
          return try await self.inner.evaluateTimeseries(request: r, options: o)
        })
    }
  }
}
