// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Parameters that control how we construct the time series for each slice.
public struct TimeseriesParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. How long should we go in the past when fetching the timeline used for
  /// forecasting each slice.
  ///
  /// This is used in combination with the
  /// [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] parameter.
  /// The time series we construct will have the following time range:
  /// `[detectionTime - forecastHistory, detectionTime + granularity]`.
  ///
  /// The forecast history might be rounded up, so that a multiple of
  /// `granularity` is used to process the query.
  ///
  /// Note: If there are not enough events in the
  /// `[detectionTime - forecastHistory, detectionTime + granularity]` time
  /// interval, the slice evaluation can fail. For more information, see
  /// [EvaluatedSlice.status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status].
  ///
  /// [google.cloud.timeseriesinsights.v1.EvaluatedSlice.status]: <doc:EvaluatedSlice/status>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]: <doc:QueryDataSetRequest/detectionTime>
  public var forecastHistory: GoogleCloudWkt.Duration? = nil

  /// Required. The time granularity of the time series (on the x-axis). Each time series
  /// point starting at time T will aggregate all events for a particular slice
  /// in *[T, T + granularity)* time windows.
  ///
  /// Note: The aggregation is decided based on the
  /// [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric] parameter.
  ///
  /// This granularity defines the query-time aggregation windows and is not
  /// necessarily related to any event time granularity in the raw data (though
  /// we do recommend that the query-time granularity is not finer than the
  /// ingestion-time one).
  ///
  /// Currently, the minimal supported granularity is 10 seconds.
  ///
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric]: <doc:TimeseriesParams/metric>
  public var granularity: GoogleCloudWkt.Duration? = nil

  /// Optional. Denotes the [name][google.cloud.timeseriesinsights.v1.EventDimension.name] of a numerical
  /// dimension that will have its values aggregated to compute the y-axis of the
  /// time series.
  ///
  /// The aggregation method must also be specified by setting the
  /// [metricAggregationMethod][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric_aggregation_method]
  /// field.
  ///
  /// Note: Currently, if the aggregation method is unspecified, we will
  /// default to SUM for backward compatibility reasons, but new implementations
  /// should set the
  /// [metricAggregationMethod][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric_aggregation_method]
  /// explicitly.
  ///
  /// If the metric is unspecified, we will use the number of events that each
  /// time series point contains as the point value.
  ///
  /// Example: Let's assume we have the following three events in our dataset:
  /// ```json
  /// {
  ///   eventTime: "2020-12-27T00:00:00Z",
  ///   dimensions: [
  ///     { name: "d1" stringVal: "v1" },
  ///     { name: "d2" stringVal: "v2" }
  ///     { name: "m1" longVal: 100 }
  ///     { name: "m2" longVal: 11 }
  ///   ]
  /// },
  /// {
  ///   eventTime: "2020-12-27T00:10:00Z",
  ///   dimensions: [
  ///     { name: "d1" stringVal: "v1" },
  ///     { name: "d2" stringVal: "v2" }
  ///     { name: "m1" longVal: 200 }
  ///     { name: "m2" longVal: 22 }
  ///   ]
  /// },
  /// {
  ///   eventTime: "2020-12-27T00:20:00Z",
  ///   dimensions: [
  ///     { name: "d1" stringVal: "v1" },
  ///     { name: "d2" stringVal: "v2" }
  ///     { name: "m1" longVal: 300 }
  ///     { name: "m2" longVal: 33 }
  ///   ]
  /// }
  /// ```
  ///
  /// These events are all within the same hour, spaced 10 minutes between each
  /// of them. Assuming our [QueryDataSetRequest][google.cloud.timeseriesinsights.v1.QueryDataSetRequest] had set
  /// [slicingParams.dimensionNames][google.cloud.timeseriesinsights.v1.SlicingParams.dimension_names] to ["d1",
  /// "d2"] and [timeseries_params.granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity] to
  /// "3600s", then all the previous events will be aggregated into the same
  /// [timeseries point][google.cloud.timeseriesinsights.v1.TimeseriesPoint].
  ///
  /// The time series point that they're all part of will have the
  /// [time][google.cloud.timeseriesinsights.v1.TimeseriesPoint.time] set to "2020-12-27T00:00:00Z" and the
  /// [value][google.cloud.timeseriesinsights.v1.TimeseriesPoint.value] populated based on this metric field:
  ///
  /// - If the metric is set to "m1" and metric_aggregation_method to SUM, then
  /// the value of the point will be 600.
  /// - If the metric is set to "m2" and metric_aggregation_method to SUM, then
  /// the value of the point will be 66.
  /// - If the metric is set to "m1" and metric_aggregation_method to AVERAGE,
  /// then the value of the point will be 200.
  /// - If the metric is set to "m2" and metric_aggregation_method to AVERAGE,
  /// then the value of the point will be 22.
  /// - If the metric field is "" or unspecified, then the value of the point
  /// will be 3, as we will simply count the events.
  ///
  /// [google.cloud.timeseriesinsights.v1.EventDimension.name]: <doc:EventDimension/name>
  /// [google.cloud.timeseriesinsights.v1.QueryDataSetRequest]: <doc:QueryDataSetRequest>
  /// [google.cloud.timeseriesinsights.v1.SlicingParams.dimension_names]: <doc:SlicingParams/dimensionNames>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]: <doc:TimeseriesParams/granularity>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric_aggregation_method]: <doc:TimeseriesParams/metricAggregationMethod>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesPoint]: <doc:TimeseriesPoint>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesPoint.time]: <doc:TimeseriesPoint/time>
  /// [google.cloud.timeseriesinsights.v1.TimeseriesPoint.value]: <doc:TimeseriesPoint/value>
  public var metric: Swift.String? = nil

  /// Optional. Together with the [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric] field, specifies how
  /// we will aggregate multiple events to obtain the value of a time series
  /// point. See the [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric] documentation for more
  /// details.
  ///
  /// If the metric is not specified or "", then this field will be ignored.
  ///
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric]: <doc:TimeseriesParams/metric>
  public var metricAggregationMethod: TimeseriesParams.AggregationMethod =
    TimeseriesParams.AggregationMethod()

  /// Initialize a new instance of `TimeseriesParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeseriesParams().with { $0.forecastHistory = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Methods by which we can aggregate multiple events by a given
  /// [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric].
  ///
  /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric]: <doc:TimeseriesParams/metric>
  public enum AggregationMethod: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Aggregate multiple events by summing up the values found in the
    /// [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric] dimension.
    ///
    /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric]: <doc:TimeseriesParams/metric>
    case sum
    /// Aggregate multiple events by averaging out the values found in the
    /// [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric] dimension.
    ///
    /// [google.cloud.timeseriesinsights.v1.TimeseriesParams.metric]: <doc:TimeseriesParams/metric>
    case average
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .sum: return 1
      case .average: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AGGREGATION_METHOD_UNSPECIFIED"
      case .sum: return "SUM"
      case .average: return "AVERAGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AggregationMethod/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AGGREGATION_METHOD_UNSPECIFIED": self = .unspecified
      case "SUM": self = .sum
      case "AVERAGE": self = .average
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AggregationMethod/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .sum
      case 2: self = .average
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .sum: return try container.encode(1)
      case .average: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.timeseriesinsights.v1.TimeseriesParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
