// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol TimeseriesInsightsControllerStub {
    func listDataSets(
      request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse

    func createDataSet(
      request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet

    func deleteDataSet(
      request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func appendEvents(
      request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse

    func queryDataSet(
      request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse

    func evaluateSlice(
      request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice

    func evaluateTimeseries(
      request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
  }
}
