// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol TimeseriesInsightsControllerStub {
    func listDataSets(
      request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse

    func createDataSet(
      request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet

    func deleteDataSet(
      request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func appendEvents(
      request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse

    func queryDataSet(
      request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse

    func evaluateSlice(
      request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice

    func evaluateTimeseries(
      request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice
  }

  class TimeseriesInsightsControllerTransport: TimeseriesInsightsControllerStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://timeseriesinsights.googleapis.com")
    }

    public func listDataSets(
      request: ListDataSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/datasets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.ListDataSetsResponse.self, from: data)
    }

    public func createDataSet(
      request: CreateDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.DataSet {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/datasets"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.dataset {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.DataSet.self, from: data)
    }

    public func deleteDataSet(
      request: DeleteDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func appendEvents(
      request: AppendEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.AppendEventsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.dataset as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.dataset' is not set or is empty")
        }
        return "/v1/\(pathVariable0):appendEvents"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.AppendEventsResponse.self, from: data)
    }

    public func queryDataSet(
      request: QueryDataSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):query"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.QueryDataSetResponse.self, from: data)
    }

    public func evaluateSlice(
      request: EvaluateSliceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.dataset as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.dataset' is not set or is empty")
        }
        return "/v1/\(pathVariable0):evaluateSlice"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.EvaluatedSlice.self, from: data)
    }

    public func evaluateTimeseries(
      request: EvaluateTimeseriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTimeseriesInsightsV1.EvaluatedSlice {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/datasets:evaluateTimeseries"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudTimeseriesInsightsV1.EvaluatedSlice.self, from: data)
    }
  }
}
